language: ruby

rvm:
 - 2.7
 - 3.0
 - 3.1
 - 3.2
 - ruby-head

env:
- QUEUE_ADAPTER='sidekiq'
- QUEUE_ADAPTER='active_job'

before_install:
 - yes | gem update --system --force
 - gem install bundler

matrix:
  allow_failures:
    - rvm: ruby-head
